# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5493ceba4419ce9549c80c90fa345efc3e42e41eddd060b80c35bb664da3810e176949d7ecd8bb8aea8f13632af5fdb675e161315dcb2da9fdd3470344fd4ffc

test:
  secret_key_base: 714851b25761063c3f950d13c93fbc54d0b9e35148b0f3b3aa104b0776676db7177ab75c304d839eb13a439e5a65c06f8366436ceea36152e02a32d18275b8c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
